#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2012 Marcel Beck
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="dnsmasq"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    configure)

        if [ -z "${2}" ]; then
            deb-systemd-helper disable ${SERVICE_XPATH_NAME}.service >/dev/null || true
            deb-systemd-invoke stop ${SERVICE_XPATH_NAME} >/dev/null || true
        fi

        # Check for XML config
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_node  "/config/services" "${SERVICE_XPATH_NAME}" ""
            omv_config_add_key "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_key "${SERVICE_XPATH}" "dns-log-queries" "0"
            omv_config_add_key "${SERVICE_XPATH}" "dhcp-enable" "0"
            omv_config_add_key "${SERVICE_XPATH}" "dns-wins" "0"
            omv_config_add_key "${SERVICE_XPATH}" "log-dhcp" "0"
            omv_config_add_key "${SERVICE_XPATH}" "domain-name" "local"
            omv_config_add_key "${SERVICE_XPATH}" "bootfile" ""
            omv_config_add_key "${SERVICE_XPATH}" "gateway" ""
            omv_config_add_key "${SERVICE_XPATH}" "default-lease-time" "168h"
            omv_config_add_key "${SERVICE_XPATH}" "ntp-servers" ""
            omv_config_add_key "${SERVICE_XPATH}" "dns-domains" ""
            omv_config_add_key "${SERVICE_XPATH}" "wins-servers" ""
            omv_config_add_key "${SERVICE_XPATH}" "dns-servers" ""
            omv_config_add_key "${SERVICE_XPATH}" "network" ""
            omv_config_add_key "${SERVICE_XPATH}" "first-ip" ""
            omv_config_add_key "${SERVICE_XPATH}" "last-ip" ""
            omv_config_add_key "${SERVICE_XPATH}" "extraoptions" ""
            omv_config_add_node "${SERVICE_XPATH}" "entries"
        fi

        # Reload rsyslogd so that it sees the new config file
        deb-systemd-invoke restart rsyslog

        chown root /usr/sbin/dnsmasq_wins
        chmod 0700 /usr/sbin/dnsmasq_wins

        # Backup dnsmasq config
        if [ ! -e /etc/default/dnsmasq-orig ]; then
            /bin/cp /etc/default/dnsmasq /etc/default/dnsmasq-orig
        fi

        # Run config
        omv-mkconf dnsmasq

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
